# Generated by Django 5.1.4 on 2025-01-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da tarefa', max_length=100)),
                ('concluida', models.BooleanField(default=False, help_text='Indica se a tarefa foi concluída')),
            ],
        ),
    ]
